SECRET_KEY = '6@pe28oo7*(r&et6w^2y=dk3i-et&5rb$p6%g=8r7y2facbg=s'

EMAIL_HOST_PASSWORD = 'django_test_pass'


AWS_ACCESS_KEY_ID = 'AKIAXTPDUE3KBVR6VV6C'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'spencer-crm'